/*
* this script is called by an early stage of the gbs pipeline, which is setting up
* the keyfile import
* It is called like
* psql -U agrbrdf -d agrbrdf -h invincible -v run="'161216_D00390_0276_AC9PM8ANXX'" -f get_run_samples.psql -q
*
*/
\t
select distinct
   sampleid
from
   biosamplelist as b join hiseqsamplesheetfact as h on
   h.biosamplelist = b.obid
where
   b.listname = :run and 
   upper(h.downstream_processing) = 'GBS';
