/*
* this script is called by an early stage of the gbs pipeline, which is setting up 
* links to the fastq files. We receive a folder name like
* gbs_fastq_link_folder is like /dataset/hiseq/scratch/postprocessing/150925_D00390_0235_BC6K0YANXX.gbs_in_progress/SQ0123.sample_in_progress/uneak_in_progress/Illumina
* - from this we look up the relevant fastq link
* It is called like
* psql -U agrbrdf -d agrbrdf -h postgres -v gbs_fastq_link_folder="'/dataset/hiseq/scratch/postprocessing/150925_D00390_0235_BC6K0YANXX.gbs_in_progress/SQ0123.sample_in_progress/uneak_in_progress/Illumina'" -f get_fastq_link.psql -q
*
*/
\t
select distinct 
   k.fastq_link
from 
   ((biosamplelist as l join biosamplelistmembershiplink m on 
   m.biosamplelist = l.obid)  join biosampleob as b on 
   b.obid = m.biosampleob ) join gbskeyfilefact as k on 
   k.biosampleob = b.obid
where
   l.listname =    split_part(
      split_part(:gbs_fastq_link_folder,'/',6),
      '.',1) and
   b.samplename =    split_part(
      split_part(:gbs_fastq_link_folder,'/',7),
      '.',1) and b.sampletype = 'Illumina GBS Library';
