# pipeline config for gbs_prism
# TODO:
# seq_root: "/dataset/2024_illumina_sequencing_e/active"
seq_root: "~/gbs_prism.dev/fake_runs"
# TODO:
# postprocessing_root: "/dataset/2024_illumina_sequencing_d/scratch/postprocessing/illumina/novaseq"
postprocessing_root: "~/gbs_prism.dev/postprocessing"

# TODO:
# gbs_backup_dir: /dataset/gseq_processing/archive/backups
gbs_backup_dir: ~/gbs_prism.dev/backups

# TODO:
# keyfiles_dir: /dataset/hiseq/active/key-files
keyfiles_dir: ~/gbs_prism.dev/key-files

# TODO
# fastq_link_farm: /dataset/hiseq/active/fastq-link-farm
fastq_link_farm: ~/gbs_prism.dev/fastq-link-farm
