# pipeline config for gbs_prism
# TODO:
# seq_root: "/dataset/2024_illumina_sequencing_e/active"
seq_root: "/home/guestsi/flexihpc/gbs_prism/fake_runs"
# TODO:
# postprocessing_root: "/dataset/2024_illumina_sequencing_d/scratch/postprocessing/illumina/novaseq"
# postprocessing_root: "/dataset/2023-legacy-sysadmin/itmp/guestsi/postprocessing"
postprocessing_root: "/home/guestsi/flexihpc/gbs_prism/postprocessing"
